// Generated by CoffeeScript 1.6.3
(function() {
  var ANIM_TIME, MAX, MIN, TICK_INTERVAL, color_interpolator, data, height, log, sin_to_unit_scale, svg, t, width, x_scale, y_scale;

  width = document.documentElement.clientWidth;

  height = document.documentElement.clientHeight;

  data = [];

  MAX = 100;

  MIN = 0;

  log = function(o) {
    return console.log(o);
  };

  svg = d3.select("body").append("svg").attr("width", width).attr("height", height);

  x_scale = d3.scale.linear().range([10, width - 10]);

  y_scale = d3.scale.linear().range([10, height - 30]);

  sin_to_unit_scale = d3.scale.linear().domain([-1, 1]);

  color_interpolator = d3.interpolateRgb("#EB0C40", "#4704D6");

  TICK_INTERVAL = 800;

  ANIM_TIME = 0.8 * TICK_INTERVAL;

  t = 0;

  setInterval(function() {
    var circle;
    data.push({
      t: t++,
      x: Math.random(),
      y: Math.random()
    });
    if (t > 60) {
      data.shift();
    }
    _.each(data, function(d) {
      var dy, y;
      y = d.y;
      dy = Math.random() * 0.2;
      if (y - dy < 0) {
        return d.y = y + dy;
      } else if (y + dy > 1) {
        return d.y = y - dy;
      } else {
        return d.y = Math.round(y * 100) & 1 ? y + dy : y - dy;
      }
    });
    circle = svg.selectAll("circle").data(data, function(d) {
      return d.t;
    });
    circle.transition().duration(ANIM_TIME).attr("cy", function(d) {
      return y_scale(d.y);
    }).style("fill", function(d) {
      return color_interpolator(sin_to_unit_scale(Math.sin(t * 0.4 + d.x * Math.PI * 2)));
    });
    circle.enter().append("circle").attr("cx", function(d) {
      return x_scale(d.x);
    }).attr("cy", function(d) {
      return y_scale(d.y);
    }).attr("r", 0).attr("opacity", 0).style("fill", function(d) {
      return color_interpolator(sin_to_unit_scale(Math.sin(t * 0.4 + d.x * Math.PI * 2)));
    }).transition().duration(ANIM_TIME).attr("r", function(d) {
      return 30 * Math.sqrt(d.x);
    }).attr("opacity", 1);
    return circle.exit().transition().duration(ANIM_TIME).attr("r", 0).attr("opacity", 0).remove();
  }, TICK_INTERVAL);

}).call(this);
