// Generated by CoffeeScript 1.6.3
(function() {
  var ANIM_TIME, MAX, MIN, TICK_INTERVAL, color_interpolator, data, height, log, svg, t, width, x_scale, y_scale;

  width = document.documentElement.clientWidth;

  height = document.documentElement.clientHeight;

  data = [];

  MAX = 100;

  MIN = 0;

  log = function(o) {
    return console.log(o);
  };

  svg = d3.select("body").append("svg").attr("width", width).attr("height", height);

  x_scale = d3.scale.linear().range([10, width - 10]);

  y_scale = d3.scale.linear().range([10, height - 10]);

  color_interpolator = d3.interpolateRgb("red", "blue");

  TICK_INTERVAL = 800;

  ANIM_TIME = 0.8 * TICK_INTERVAL;

  t = 0;

  setInterval(function() {
    var circle;
    data.push({
      t: t++,
      x: Math.random()
    });
    if (t > 60) {
      data.shift();
    }
    _.each(data, function(d) {
      var dx, x;
      x = d.x;
      dx = Math.random() * 0.2;
      if (x - dx < 0) {
        return d.x = x + dx;
      } else if (x + dx > 1) {
        return d.x = x - dx;
      } else {
        return d.x = Math.round(x * 100) & 1 ? x + dx : x - dx;
      }
    });
    circle = svg.selectAll("circle").data(data, function(d) {
      return d.t;
    });
    circle.transition().duration(ANIM_TIME).attr("cy", function(d) {
      return y_scale(d.x);
    });
    circle.enter().append("circle").attr("cx", function(d) {
      return x_scale(d.x);
    }).attr("cy", function(d) {
      return y_scale(d.x);
    }).style("fill", function(d) {
      return color_interpolator(d.x);
    }).attr("opacity", 0).attr("r", 0).transition().duration(ANIM_TIME).attr("r", function(d) {
      return 30 * Math.sqrt(d.x);
    }).attr("opacity", 1);
    return circle.exit().transition().duration(ANIM_TIME).attr("r", 0).attr("opacity", 0).remove();
  }, TICK_INTERVAL);

}).call(this);
